name: GinacLean CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

permissions:
  contents: write

jobs:
  lean4:
    name: ginac-lean
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64]
      fail-fast: false
    env:
      SHELLOPTS: igncr
    steps:
      # Following https://github.com/axboe/fio/blob/master/.github/workflows/ci.yml
      - name: git config line endings (Windows)
        if: ${{ contains( matrix.os, 'windows' ) }}
        run: git config --global core.autocrlf input
      - name: Install msys2 toolchain (Windows)
        if: ${{ startsWith(matrix.os, 'windows') }}
        uses: msys2/setup-msys2@v2
        with:
          cache: false
          install: >
            git
            base-devel
            mingw-w64-${{matrix.arch}}-clang
            mingw-w64-${{matrix.arch}}-toolchain
            mingw-w64-${{matrix.arch}}-lld
      - name: install elan on Ubuntu and macOS
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | bash -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: install elan on Windows
        if: matrix.os == 'windows-latest'
        run: |
          curl -O --location https://raw.githubusercontent.com/leanprover/elan/master/elan-init.ps1
          .\elan-init.ps1 -NoPrompt 1 -DefaultToolchain none
          echo "$HOME\.elan\bin" >> $env:GITHUB_PATH
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.11
      - name: Set up cache for deps
        uses: actions/cache@v3
        with:
          path: .lake
          key: cache-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            cache-${{ runner.os }}-
      - name: package install
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt update
            sudo apt install -y curl wget git git-lfs clang lld libc++-dev
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "Running on macOS"
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "Running on Windows"
          else
            echo "Unsupported OS"
          fi
      - name: pip install
        shell: bash
        run: |
          pip install -r codegen/requirements.txt -r codegen/requirements-dev.txt -r codegen/requirements-tests.txt
      # - name: run pre-commit
      #   run: |
      #     pre-commit run --all-files
      # - name: build ginac
      #   run: |
      #     bash scripts/build_ginac.sh
      # - name: run codegen tests
      #   run: |
      #     pytest codegen/tests
      # - name: check ginac
      #   run: |
      #     # Not all tests are passing on mac for now
      #     if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
      #       bash scripts/check_ginac.sh
      #     fi
      - name: lake build
        shell: bash
        run: |
          # avoid cache causing unclean build
          lake run clear
          lake build
      - name: lake upload
        if: github.event_name == 'release'
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            # lake upload reports "tar: .: file changed as we read it" on Ubuntu
            # https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/lake.20upload.20for.20Cloud.20Release
            tar -c -z --exclude=*.tar.gz --exclude=*.tar.gz.trace -f /tmp/linux-64.tar.gz -C ./build .
            gh release upload ${{ github.ref_name }} /tmp/linux-64.tar.gz --clobber
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            lake upload ${{ github.ref_name }}
          else
            echo "Unsupported OS"
          fi
        shell: bash

        env:
          GH_TOKEN: ${{ github.token }}

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v1
      #   with:
      #     path: ./dist

  # Deployment job
  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: lean4
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v1
